# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientmain.ui'
#
# Created: Sat Oct  9 16:06:53 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 561)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 300, 1051, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hudHorizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.hudHorizontalLayout.setObjectName("hudHorizontalLayout")
        self.chatTabWidget = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.chatTabWidget.setEnabled(True)
        self.chatTabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.chatTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.chatTabWidget.setUsesScrollButtons(False)
        self.chatTabWidget.setDocumentMode(False)
        self.chatTabWidget.setTabsClosable(False)
        self.chatTabWidget.setObjectName("chatTabWidget")
        self.geralChatTab = QtGui.QWidget()
        self.geralChatTab.setObjectName("geralChatTab")
        self.verticalLayoutWidget = QtGui.QWidget(self.geralChatTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 341, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.geralChatTabVerticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.geralChatTabVerticalLayout.setObjectName("geralChatTabVerticalLayout")
        self.geralChatTabTextBrowser = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.geralChatTabTextBrowser.setObjectName("geralChatTabTextBrowser")
        self.geralChatTabVerticalLayout.addWidget(self.geralChatTabTextBrowser)
        self.geralChatTabLineEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.geralChatTabLineEdit.setObjectName("geralChatTabLineEdit")
        self.geralChatTabVerticalLayout.addWidget(self.geralChatTabLineEdit)
        self.chatTabWidget.addTab(self.geralChatTab, "")
        self.aliancaChatTab = QtGui.QWidget()
        self.aliancaChatTab.setObjectName("aliancaChatTab")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.aliancaChatTab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 341, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.aliancaChatTabverticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.aliancaChatTabverticalLayout.setObjectName("aliancaChatTabverticalLayout")
        self.aliancaChatTabTextBrowser = QtGui.QTextBrowser(self.verticalLayoutWidget_3)
        self.aliancaChatTabTextBrowser.setObjectName("aliancaChatTabTextBrowser")
        self.aliancaChatTabverticalLayout.addWidget(self.aliancaChatTabTextBrowser)
        self.aliancaChatTabLineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.aliancaChatTabLineEdit.setObjectName("aliancaChatTabLineEdit")
        self.aliancaChatTabverticalLayout.addWidget(self.aliancaChatTabLineEdit)
        self.chatTabWidget.addTab(self.aliancaChatTab, "")
        self.hudHorizontalLayout.addWidget(self.chatTabWidget)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hudHorizontalLayout.addItem(spacerItem)
        self.playersTabWidget = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.playersTabWidget.setObjectName("playersTabWidget")
        self.jogadoresPlayersTab = QtGui.QWidget()
        self.jogadoresPlayersTab.setObjectName("jogadoresPlayersTab")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.jogadoresPlayersTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 341, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.jogadoresPlayersTabVerticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.jogadoresPlayersTabVerticalLayout.setObjectName("jogadoresPlayersTabVerticalLayout")
        self.jogadoresPlayersTabListWidget = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.jogadoresPlayersTabListWidget.setObjectName("jogadoresPlayersTabListWidget")
        self.jogadoresPlayersTabVerticalLayout.addWidget(self.jogadoresPlayersTabListWidget)
        self.playersTabWidget.addTab(self.jogadoresPlayersTab, "")
        self.amigosPlayersTab = QtGui.QWidget()
        self.amigosPlayersTab.setObjectName("amigosPlayersTab")
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.amigosPlayersTab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(-1, -1, 341, 181))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.amigosPlayersTabVerticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.amigosPlayersTabVerticalLayout.setObjectName("amigosPlayersTabVerticalLayout")
        self.amigosPlayersTabListWidget = QtGui.QListWidget(self.verticalLayoutWidget_4)
        self.amigosPlayersTabListWidget.setObjectName("amigosPlayersTabListWidget")
        self.amigosPlayersTabVerticalLayout.addWidget(self.amigosPlayersTabListWidget)
        self.playersTabWidget.addTab(self.amigosPlayersTab, "")
        self.bloqueadosPlayersTab = QtGui.QWidget()
        self.bloqueadosPlayersTab.setObjectName("bloqueadosPlayersTab")
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.bloqueadosPlayersTab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(-1, -1, 341, 181))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.bloqueadosPlayersTabVerticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.bloqueadosPlayersTabVerticalLayout.setObjectName("bloqueadosPlayersTabVerticalLayout")
        self.bloqueadosPlayersTabListWidget = QtGui.QListWidget(self.verticalLayoutWidget_5)
        self.bloqueadosPlayersTabListWidget.setObjectName("bloqueadosPlayersTabListWidget")
        self.bloqueadosPlayersTabVerticalLayout.addWidget(self.bloqueadosPlayersTabListWidget)
        self.playersTabWidget.addTab(self.bloqueadosPlayersTab, "")
        self.hudHorizontalLayout.addWidget(self.playersTabWidget)
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1051, 511))
        self.graphicsView.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.graphicsView.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.chatTabWidget.setCurrentIndex(0)
        self.playersTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Corvogame", None, QtGui.QApplication.UnicodeUTF8))
        self.chatTabWidget.setTabText(self.chatTabWidget.indexOf(self.geralChatTab), QtGui.QApplication.translate("MainWindow", "Geral", None, QtGui.QApplication.UnicodeUTF8))
        self.chatTabWidget.setTabText(self.chatTabWidget.indexOf(self.aliancaChatTab), QtGui.QApplication.translate("MainWindow", "Aliança", None, QtGui.QApplication.UnicodeUTF8))
        self.playersTabWidget.setTabText(self.playersTabWidget.indexOf(self.jogadoresPlayersTab), QtGui.QApplication.translate("MainWindow", "Jogadores", None, QtGui.QApplication.UnicodeUTF8))
        self.playersTabWidget.setTabText(self.playersTabWidget.indexOf(self.amigosPlayersTab), QtGui.QApplication.translate("MainWindow", "Amigos", None, QtGui.QApplication.UnicodeUTF8))
        self.playersTabWidget.setTabText(self.playersTabWidget.indexOf(self.bloqueadosPlayersTab), QtGui.QApplication.translate("MainWindow", "Bloqueados", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

